package com.prism.trace;

/**
 * The structured event vocabulary. A closed enum, so trace queries and the
 * Glass Box UI can rely on real values instead of arbitrary strings.
 */
public enum TraceEventType {
    DOCUMENT_UPLOADED,
    CHUNK_CREATED,
    EXTRACTION_STARTED,
    LLM_REQUEST,
    LLM_RESPONSE,
    JSON_PARSED,
    VALIDATION_FAILED,
    QUARANTINED,
    TRIPLE_PROPOSED,
    CLAIM_PROPOSED,
    TRIPLE_APPROVED,
    TRIPLE_REJECTED,
    CLAIM_APPROVED,
    CLAIM_REJECTED,
    RETRIEVAL_STARTED,
    RETRIEVAL_COMPLETED,
    RULE_ANALYSIS,
    LLM_JUDGMENT,
    VERDICT_CREATED,
    HUMAN_ADJUDICATION,
    CONTRADICTION_CREATED,
    DEBATE_CREATED,
    DEBATE_STARTED,
    SKEPTIC_BRIEF_CREATED,
    ARGUMENT_CREATED,
    ARGUMENT_FAILED,
    ARGUMENT_WEIGHTED,
    ROUND_COMPLETED,
    SYNTHESIS_STARTED,
    SYNTHESIS_COMPLETED,
    CHAT_RETRIEVAL,
    CHAT_RESPONSE,
    CITATION_VALIDATED,
    CITATION_REJECTED,
    GRAPH_COMPUTED,
    PIPELINE_FAILED,
    SYSTEM_RECOVERY
}
